// The widget catalogue lives in @relay/protocol so hosts validate dashboard tiles with the same
// schema the phone renders; this module keeps the app's local import path.
export {
  MAX_CHILDREN,
  MAX_DEPTH,
  parseWidget,
  type AudioSpec,
  type BadgeSpec,
  type CardSpec,
  type ChartSpec,
  type CompareSpec,
  type DiffSpec,
  type EmailSpec,
  type EmailsSpec,
  type PrSpec,
  type GallerySpec,
  type RowsSpec,
  type Series,
  type StackSpec,
  type StatSpec,
  type TextSpec,
  type TicketSpec,
  type TicketsSpec,
  type VideoSpec,
  type Tone,
  type WidgetSpec,
} from "@relay/protocol";
